### ISSUE TITLE
Detect Loops

### ISSUE THREAD

**Issue by philippfromme** [camunda/bpmnlint-plugin-camunda-compat#100]
#### The rule should detect the following modeling patterns

In order to prevent hard-to-debug runtime errors Zeebe will introduce loop detection (cf. https://github.com/camunda/zeebe/pull/13025). The linter should be able to detect loops so they can be fixed before deployment.

#### How does the rule improve the BPMN diagram?

Loops are detected and can be fixed.

#### Rule Details

* Name: `no-loop`
* Default notification level: `error`

**Comment by nikku** [comment]
Closed via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/102.
