### ISSUE TITLE
Validate start forms in Camunda 8.3

### ISSUE THREAD

**Issue by nikku** [camunda/bpmnlint-plugin-camunda-compat#106]
#### The rule should detect the following modeling patterns

* Validate that start forms are only supported in Camunda 8.3

As a result [this example diagram](https://github.com/camunda/bpmnlint-plugin-camunda-compat/files/12013132/start-form-example.bpmn.txt) should yield a human readable error:

> A form on a <Start Event> is only supported by Camunda 8.3 or newer

#### How does the rule improve the BPMN diagram?

Ensure users can discover if start forms are supported.

#### Rule Details

* Name: `start-form`
* Default notification level: `error`

#### What alternatives did you consider? 

None.

**Comment by christian-konrad** [comment]
@nikku this is done right?

**Comment by marstamm** [comment]
Merged via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/115, still needs to be implemented in `@camunda/linting` (cf. https://github.com/camunda/linting/pull/75)
