### ISSUE TITLE
Validate That Throwing Link Event Has Corresponding Catching Link Event

### ISSUE THREAD

**Issue by philippfromme** [camunda/bpmnlint-plugin-camunda-compat#129]
Validation of link events was introduced with https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/62. Zeebe validates that for a throwing link event there is a catching link event with the corresponding `name`. The `link-event` rule should validate this, too.

---

Follow-up to https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/62

**Comment by nikku** [comment]
This should be a core validation rule, as none of this is Zeebe specific, but how the BPMN works.

**Comment by nikku** [comment]
Closed in favor of https://github.com/bpmn-io/bpmnlint/pull/128.
