### ISSUE TITLE
`secrets` Rule Should Report Warning Instead of Error

### ISSUE THREAD

**Issue by Oleksiivanov** [camunda/bpmnlint-plugin-camunda-compat#132]
`secrets.FOO` produces a lint error stating that the secret expression is not valid. In fact, this format is currently supported but will be deprecated in the future. Therefore the lint error should be a warning instead. The message should indicate the future deprecation and the new format (`{{secrets.FOO}}`).

---

Follow-up to https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/119

**Comment by bastiankoerber** [comment]
can we change it to warning, since we get a lot of support requests.
We are still supporting the old format, but we want to deprecate it, that's why we should throw a warning and not an error

**Comment by philippfromme** [comment]
The information about a currently supported pattern we want to deprecate was missing from the original issue. This is vital information. The error message should then be adjusted as well (e.g. `The secret format you're using will be deprecated in future versions of Camunda 8. Use {{secrets.FOO}} instead.`).

**Comment by bastiankoerber** [comment]
looks good, are we adding a hint in our documentation as well?

**Comment by philippfromme** [comment]
> as was also described here

I cannot find that information in the original pull request. I was assuming that we introduced secrets altogether. We can ship a patch release adjusting the error to be a warning with the adjusted message.

**Comment by philippfromme** [comment]
Since we can't show warnings in the properties panel right now I will disable the rule until we're ready to report warnings instead of errors.

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/133. We'll enable the rule once we've fixed the issues.
