### ISSUE TITLE
Validate `formId` Introduced by Camunda 8.3

### ISSUE THREAD

**Issue by philippfromme** [camunda/bpmnlint-plugin-camunda-compat#144]
Camunda 8.3 supports two different types of forms:

* embedded through `formKey`
* linked through `formId`

These two are exclusive. `formId` is not supported by older versions of Camunda 8. Linting should indicate that.

---

Related to https://github.com/camunda/camunda-modeler/issues/3656

**Comment by marstamm** [comment]
closes via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/145
