### ISSUE TITLE
`Form must be defined` should be a warning

### ISSUE THREAD

**Issue by barmac** [camunda/bpmnlint-plugin-camunda-compat#154]
## Problem

Currently, a missing form is marked as an error. However, one can still deploy a diagram to Camunda 8.4.1 (this one I checked) even if a form is not defined. Moreover, there is a use case for such underimplemented form as reported by @NPDeehan in https://camunda.slack.com/archives/C0693F1NFK5/p1706613498853189.

## Expected behavior

The linting rule should report a warning as we still want to encourage the users to define forms, but don't want to overreact as deployment can still succeed if form is missing.

**Comment by nikku** [comment]
Received [additional feedback](https://camunda.slack.com/archives/C043W5V88M7/p1707828083089759) on this.

**Comment by nikku** [comment]
Moving this to `ready` as we've seen a bunch of internals already negatively affected by this.

**Comment by philippfromme** [comment]
So the agreement is:

* report warning when `zeebe:UserTaskDefinition` is missing
* report error when `zeebe:UserTaskDefinition` exists but is missing required properties (either `formId` or `formKey`)

This means we have to split the rule as you can only set the level (`error` or `warn`) for a rule, not for individual reports.

**Comment by nikku** [comment]
Closed via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/157.

@philippfromme Let's go ahead and integrate this.
