### ISSUE TITLE
Ensure eslint bpmnio plugin works correctly in this repo

### ISSUE THREAD

**Issue by MaxTru** [camunda/bpmnlint-plugin-camunda-compat#16]
**What**

Ensure eslint bpmnio plugin works correctly in this repo

**Why**

Apparently our eslint linting rules are not applied here. See: https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/15#discussion_r829229996

**Comment by nikku** [comment]
Works nowadays: 

![image](https://user-images.githubusercontent.com/58601/188116413-2ce91cde-f92e-49f7-9fb1-dcb91a38a552.png)
