### ISSUE TITLE
`no-priority-definition` and `priority-definition` zeebe linting rules

### ISSUE THREAD

**Issue by Skaiir** [camunda/bpmnlint-plugin-camunda-compat#170]
#### The rule should detect the following modeling patterns

```xml
<userTask id="" name="">
  <bpmn:extensionElements>
    <zeebe:priorityDefinition priority="15" />
  </bpmn:extensionElements>
</userTask> 
```

#### How does the rule improve the BPMN diagram?

We need to ensure that the priority is configured properly and if not, handled as a linting error. 

#### Rule Details

* Name: no-priority-definition
  * Default notification level: `error`
  * Details: prior to 8.6, this extension element should be disallowed
* Name: priority-definition
  * Default notification level: `error`
  * Details: from 8.6 onwards, this extension element, if it exists, should be validated to either be an integer or a  feel expression

#### What alternatives did you consider? 

n/a

#### Context

Parent issue: https://github.com/camunda/camunda-modeler/issues/4450

**Comment by barmac** [comment]
Published as v2.24.0
