### ISSUE TITLE
Smooth 8.7 migration linting: `no-job-worker-user-task`

### ISSUE THREAD

**Issue by Skaiir** [camunda/bpmnlint-plugin-camunda-compat#177]
#### The rule should detect the following modeling patterns

* Incorrect
```
    <bpmn:userTask id="Activity_18h160l" name="Job worker">
      <bpmn:extensionElements>
        <zeebe:formDefinition formKey="X" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_12l5h67</bpmn:incoming>
      <bpmn:outgoing>Flow_1g357gi</bpmn:outgoing>
    </bpmn:userTask>
```

* Correct
```
    <bpmn:userTask id="Activity_1s8r6ix" name="Zeebe">
      <bpmn:extensionElements>
        <zeebe:userTask />
        <zeebe:formDefinition externalReference="Y" />
      </bpmn:extensionElements>
      <bpmn:incoming>Flow_16godsg</bpmn:incoming>
      <bpmn:outgoing>Flow_1w0i494</bpmn:outgoing>
    </bpmn:userTask>
```

The key difference being the detection of the `zeebe:userTask` element.

#### How does the rule improve the BPMN diagram?

Following 8.7, non-zeebe user-tasks are no longer going to be supported. So we need to indicate this as an error.

#### Rule Details

* Name: `no-job-worker-user-task`
* Default notification level: `error`

#### What alternatives did you consider? 

n/a

**Comment by jarekdanielak** [comment]
Is there any timeline for this? Do you plan to contribute or should somebody from bpmn-io team pick it up?

**Comment by Skaiir** [comment]
@jarekdanielak I'm taking care of it, should have this and https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/178 PR'd today.

**Comment by Skaiir** [comment]
Relating to https://github.com/camunda/product-hub/issues/2126
