### ISSUE TITLE
Smooth 8.7 migration linting: `mixed-user-task-impl`

### ISSUE THREAD

**Issue by Skaiir** [camunda/bpmnlint-plugin-camunda-compat#178]
_Supports https://github.com/camunda/product-hub/issues/2126._

#### The rule should detect the following modeling patterns

Mixed use of job workers and zeebe user tasks

*  Incorrect
```
    <bpmn:userTask id="Activity_18h160l" name="Job worker">
    </bpmn:userTask>
    <bpmn:userTask id="Activity_18h160l" name="Job worker">
      <bpmn:extensionElements>
        <zeebe:userTask />
      </bpmn:extensionElements>
    </bpmn:userTask>

```

* Correct
```
    <bpmn:userTask id="Activity_18h160l" name="Job worker">
    </bpmn:userTask>
    <bpmn:userTask id="Activity_18h160l" name="Job worker">
    </bpmn:userTask>
```
OR
```
    <bpmn:userTask id="Activity_18h160l" name="Job worker">
      <bpmn:extensionElements>
        <zeebe:userTask />
      </bpmn:extensionElements>
    </bpmn:userTask>
    <bpmn:userTask id="Activity_18h160l" name="Job worker">
      <bpmn:extensionElements>
        <zeebe:userTask />
      </bpmn:extensionElements>
    </bpmn:userTask>
 ```

#### How does the rule improve the BPMN diagram?

With the deprecation of user tasks soon, and since it can be generally challenging to mixed implementations, we should discourage it via warnings, but not outright error it as it somewhat supported (for now anyways).

#### Rule Details

* Name: mixed-user-task-impl
* Default notification level: `error|warn|off`

#### What alternatives did you consider? 

n/a

**Comment by Skaiir** [comment]
Relating to https://github.com/camunda/product-hub/issues/2126

**Comment by nikku** [comment]
@Skaiir I guess you'll still work on this?

**Comment by barmac** [comment]
In the last discussion, we established that we may not need this rule, because all job-worker based tasks managed by Camunda are already marked as deprecated. So the potential contribution in this rule would be a second error on such tasks + an error on the preferred task type (Camunda user task). WDYT? @Skaiir

**Comment by Skaiir** [comment]
Forgot to close the issue, but yes we quite clearly and unanimously agreed on this, this would be redundant.
