### ISSUE TITLE
Ensure that linting error about "Lane" guides user to the lane

### ISSUE THREAD

**Issue by andreasgeier** [camunda/bpmnlint-plugin-camunda-compat#24]
We should improve the "lane" error message by guiding the user to the lane. Currently, the message references the process.

![Screen Shot 2022-04-06 at 08 28 30](https://user-images.githubusercontent.com/938244/161909618-ae3cffbd-41b4-471f-b972-3971f467d36d.png)

**Comment by andreasgeier** [comment]
This would cause multiple errors if multiple lanes per process are used. But I assume this is acceptable because the user has to solve this issue lane by lane (e.g. to delete a lane it must be selected).

**Comment by philippfromme** [comment]
Lanes are actually supported by Zeebe. The engine will not throw an error when deploying a BPMN with lanes. https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/26 will make this issue obsolete.
