### ISSUE TITLE
Add Rule to Allow Connectors for Camunda 8 Only

### ISSUE THREAD

**Issue by philippfromme** [camunda/bpmnlint-plugin-camunda-compat#30]
* [x] allow connectors (element templates) for Camunda 8
* [x] disallow connectors (element templates) for Camunda 8 (Zeebe 1.0, 1.1 and 1.3)

The assumption is that connectors are synonymous with element templates (`modeler:template` attribute).

---

Depends on https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/29
Related to https://github.com/camunda/web-modeler/issues/1246

**Comment by pinussilvestrus** [comment]
Are we using this rule in Desktop Modeler as well? Because using local element templates does not necessarily mean I use a connector.

**Comment by philippfromme** [comment]
> Are we using this rule in Desktop Modeler as well? Because using local element templates does not necessarily mean I use a connector.

Good point. Introducing this rule would mean that I'd get an error saying connectors aren't supported when applying a template. Connector templates aren't even available in the desktop modeler so the rule would only be useful if I exported a diagram from the web modeler and then opened it in the desktop modeler. The error regarding the support of connectors would already have shown up in the web modeler. What do you think @MaxTru @nikku @christian-konrad

**Comment by nikku** [comment]
> Are we using this rule in Desktop Modeler as well? Because using local element templates does not necessarily mean I use a connector.

Templates are not supported with <= Zeebe 1.3, with or without "connectors". 

We should keep it simple for the moment, and just ship this rule :slightly_smiling_face:.
