### ISSUE TITLE
Include no-bpmndi rule

### ISSUE THREAD

**Issue by MaxTru** [camunda/bpmnlint-plugin-camunda-compat#35]
# Problem

We already had multiple cases where deployments to Camunda failed or went to unexpected results, because of missing bpmndi info.

See:
* https://camunda.slack.com/archives/C034N0E5YCX/p1654165797392569
* https://jira.camunda.com/plugins/servlet/samlsso?redirectTo=%2Fbrowse%2FSUPPORT-9121

# Solution proposal

The `no-bpmndi` rule detects such cases: https://github.com/bpmn-io/bpmnlint/blob/master/rules/no-bpmndi.js. We could easily include it in our standard camunda-compat ruleset. It also fits well, since it ensures, that the diagram can successfully be deployed to Camunda.

**Comment by MaxTru** [comment]
Risk: the `no-bpmndi` rule traverses the entire model, hence it might have performance implications on large diagrams. @nikku do you think this could be a problem? If so, I could validate with our super large collapsed subprocess diagrams.

**Comment by MaxTru** [comment]
@MaxTru to test with the deeply nested diagram (cc. @marstamm )

**Comment by MaxTru** [comment]
Maybe have it in the camunda/linting repo instead (cc. @philippfromme )

**Comment by marstamm** [comment]
The big BPMN file can be found here: https://jira.camunda.com/browse/SUPPORT-13125

I'm not sure if we can publish it in a public repo, as it was created by a customer (but all data was redacted)

**Comment by MaxTru** [comment]
Move over to https://github.com/camunda/linting/issues/2
