### ISSUE TITLE
Validate BPMN elements unsupported for execution

### ISSUE THREAD

**Issue by nikku** [camunda/bpmnlint-plugin-camunda-compat#46]
__What should we do?__

* [ ] Mark elements that are not supported for execution in C8 as incompatible

__Why should we do it?__

As [decided](https://github.com/bpmn-io/internal-docs/issues/644) we want to allow our users to [model all BPMN elements in C8 diagrams](https://github.com/camunda/camunda-bpmn-js/issues/166) and resort to linting to identify incompatible (for execution) elements.

**Comment by marstamm** [comment]
Done in https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/52
