### ISSUE TITLE
Add validation rules for link events

### ISSUE THREAD

**Issue by marstamm** [camunda/bpmnlint-plugin-camunda-compat#62]
Camunda 8.2 supports link events. We should introduce lint rule(s) that support the user in using the link event correctly.

- [x] require the `name` property to be set on both catching and throwing link events
- [x] validate that there isn't more than one catching link event with the same `name`
- [ ] ~validate that catching and throwing events are children of the same process (_Link
Event uses are limited to a single Process level (i.e., they cannot link a
parent Process with a Sub-Process)_)~ Zeebe doesn't validate this either

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/122.
