### ISSUE TITLE
Disallow Condition If Sequence Flow Is Not Exclusive or Inclusive Gateway

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/bpmnlint-plugin-camunda-compat#82]
#### The rule should detect the following modeling patterns

Incorrect: Camunda 8.1 will reject this:
[converted-c8-conditional-flow.bpmn.txt](https://github.com/camunda/bpmnlint-plugin-camunda-compat/files/10850906/converted-c8-conditional-flow.bpmn.txt)

```
'converted-c8-conditional-flow.bpmn': - Element: DoSomethingTask
    - ERROR: Conditional sequence flows are only supported at exclusive or inclusive gateway
```

Correct: Camunda 8.1 will accept this:
[converted-c8-inclusive-gateway.bpmn.txt](https://github.com/camunda/bpmnlint-plugin-camunda-compat/files/10850927/converted-c8-inclusive-gateway.bpmn.txt)

In addition, we consider modeling implicit gateways a bad practice, so even if zeebe will support conditional flows, this rule would still apply as warning or info.

#### How does the rule improve the BPMN diagram?

This rule will prevent users from creating undeployable diagrams.

#### Rule Details

* Name: no-conditional-flows
* Default notification level: `error`

**Comment by marstamm** [comment]
The rule makes sense, thanks for suggesting it

**Comment by nikku** [comment]
> In addition, we consider modeling implicit gateways a bad practice, so even if zeebe will support conditional flows, this rule would still apply as warning or info.

This would be "modeling guidance" then. With this plug-in we strictly validated compatibility for execution.

**Comment by nikku** [comment]
Interestingly enough Zeebe does not fail on default flows, only conditional :see_no_evil. This diagram deploys just fine, but makes no sense without condition support:

![image](https://github.com/camunda/bpmnlint-plugin-camunda-compat/assets/58601/2430fd65-594b-4026-9146-d004d66f8d9c)

**Comment by nikku** [comment]
Closed via https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/97.

**Comment by philippfromme** [comment]
> - Element: Flow_1f2h1nt > conditionExpression
>     - ERROR: Expected expression but found static value ''. An expression must start with '=' (e.g. '=').
> [ deploy-error ] 16/5/2023 18:0:38

How did you end up with an empty expression? The `conditionExpression` shouldn't exist unless there is a value.

**Comment by nikku** [comment]
Change a flow into a conditional flow.
