### ISSUE TITLE
Support Signal Intermediate Throw and End Event in Camunda 8.3

### ISSUE THREAD

**Issue by philippfromme** [camunda/bpmnlint-plugin-camunda-compat#93]
Camunda 8.3 is going to support signal intermediate throw and end events.

* [x] add Camunda 8.3 config
* [x] adjust `element-type` configuration to support signal intermediate throw and end events in Camunda 8.3
* [x] add `signal-reference` rule to lint signal reference and name

---

Related to https://github.com/camunda/camunda-modeler/issues/3555

**Comment by marstamm** [comment]
closed via https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/93
